# Generated by Django 5.0.dev20230420102433 on 2023-04-22 17:26

import django.db.models.deletion
import places.fields
import portfolio.models
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=9, max_length=9, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=35)),
                ('category', models.CharField(choices=[('AL', 'Anniversary & Life Moments'), ('CP', 'Commercial & Product'), ('EW', 'Engagement & Wedding'), ('SH', 'Studio & Headshots'), ('TV', 'Travel & Vacation'), ('JD', 'Journalism & Documentary'), ('MO', 'Modern Outdoor'), ('CE', 'Conference & Event'), ('DR', 'Drone Shots'), ('PT', 'Photo Retouch'), ('VE', 'Video Editing')], max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('deliverables', models.TextField(blank=True, max_length=1000)),
                ('equipment', models.TextField(blank=True, max_length=500)),
                ('service', models.TextField(blank=True, max_length=1000)),
                ('photo', models.FileField(blank=True, upload_to=portfolio.models.upload_location_gig)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255)),
                ('location', places.fields.PlacesField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default='default.jpg', upload_to=portfolio.models.upload_location_portfolio)),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True)),
                ('about', models.TextField(blank=True, max_length=140)),
                ('service', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.URLField(blank=True)),
                ('social_ig', models.URLField(blank=True)),
                ('social_fb', models.URLField(blank=True)),
                ('social_yt', models.URLField(blank=True)),
                ('social_vm', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('master', 'Master')], default='standard', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='portfolio.gig')),
            ],
        ),
    ]
