# Generated by Django 4.2 on 2023-04-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_gig_options_alter_portfolio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('AL', 'Anniversary & Life Moments'), ('CP', 'Commercial & Product'), ('EW', 'Engagement & Wedding'), ('SP', 'Studio & Portrait'), ('TV', 'Travel & Vacation'), ('JD', 'Journalism & Documentary'), ('EC', 'Event & Conference'), ('DR', 'Drone Shots'), ('PT', 'Photo Retouch'), ('VE', 'Video Editing')], max_length=255),
        ),
    ]
